### ISSUE TITLE
A locally correct answer that can't pass the auto-grader for HW4

### ISSUE THREAD

**Issue by an-ju** [saasbook/rag#108] opened 2017-07-10 15:29 UTC
We have some students reporting that answers that work locally can't pass the auto-grader. An example can be found in [this file](https://www.dropbox.com/s/0upu9ln0mhlimjm/features.zip?dl=0). Another example would be calling check method with ratings[#{rating}]. We believe this is due to the version of Cucumber and Cypabara of the auto-grader.

**Comment by tansaku** [comment] 2017-07-10 16:25
thanks for reporting this @an-ju 

Just to be sure we're talking about https://github.com/saasbook/hw-bdd-cucumber right?

note that having things passing locally for this homework do not guarantee that they will pass on the  grader since this is a MUTATION GRADER, that experimentally breaks the code and expects it to fail in certain ways.

For clarity could you paste in the error that we get on the grader from submitting that assignment?

**Comment by an-ju** [comment] 2017-07-10 16:34
Yes. This is the homework.

Oh, I didn't know that. I'll post a more detailed explanation ASAP.

**Comment by an-ju** [comment] 2017-07-10 17:18
This is the output from the auto-grader:

```
Your submission was recorded at 2017-07-10 17:06:48 +0000 : submission is on time.
Score: 0.8500000000000001/1.0
--------------------------------------------------------------------------------
Test passed. (+0.2)
--------------------------------------------------------------------------------
The following required failures were not detected:
 - all ratings or checkboxes selected
with the following modifications:
 - results = [G, PG-13] movies
| Disabling profiles...
| Feature: display list of movies filtered by MPAA rating
|   
|   As a concerned parent
|   So that I can quickly browse movies appropriate for my family
|   I want to see movies matching only certain MPAA ratings
| 
|   Background: movies have been added to database # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/filter_movie_list.feature:7
|     Given the following movies exist:            # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/movie_steps.rb:3
|       | title                   | rating | release_date |
|       | Aladdin                 | G      | 25-Nov-1992  |
|       | The Terminator          | R      | 26-Oct-1984  |
|       | When Harry Met Sally    | R      | 21-Jul-1989  |
|       | The Help                | PG-13  | 10-Aug-2011  |
|       | Chocolat                | PG-13  | 5-Jan-2001   |
|       | Amelie                  | R      | 25-Apr-2001  |
|       | 2001: A Space Odyssey   | G      | 6-Apr-1968   |
|       | The Incredibles         | PG     | 5-Nov-2004   |
|       | Raiders of the Lost Ark | PG     | 12-Jun-1981  |
|       | Chicken Run             | G      | 21-Jun-2000  |
|     And I am on the RottenPotatoes home page     # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:44
| 
|   Scenario: restrict to movies with 'PG' or 'R' ratings # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/filter_movie_list.feature:24
|     Given I check the following ratings: PG, R          # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/movie_steps.rb:29
|     And I uncheck the following ratings: G, PG-13       # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/movie_steps.rb:29
|     Then I press "ratings_submit"                       # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:52
|     Then I should see "The Terminator"                  # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:105
|       expected to find text "The Terminator" in "Rotten Potatoes! All Movies Include: G PG PG-13 NC-17 R Movie Title Rating Release Date More Info Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Aladdin G 1992-11-25 00:00:00 UTC More about Aladdin The Help PG-13 2011-08-10 00:00:00 UTC More about The Help Chocolat PG-13 2001-01-05 00:00:00 UTC More about Chocolat 2001: A Space Odyssey G 1968-04-06 00:00:00 UTC More about 2001: A Space Odyssey Chicken Run G 2000-06-21 00:00:00 UTC More about Chicken Run Add new movie" (RSpec::Expectations::ExpectationNotMetError)
|       ./submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:107:in `/^(?:|I )should see "([^"]*)"$/'
|       submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/filter_movie_list.feature:33:in `Then I should see "The Terminator"'
|     But I should not see "The Help"                     # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:124
| 
|   #  And I should see
|   #  | title                   | rating | release_date |
|   #  | The Terminator          | R      | 26-Oct-1984  |
|   #  | When Harry Met Sally    | R      | 21-Jul-1989  |
|   #  | Amelie                  | R      | 25-Apr-2001  |
|   #  | The Incredibles         | PG     | 5-Nov-2004   |
|   #  | Raiders of the Lost Ark | PG     | 12-Jun-1981  |
|   #  And I should not see
|   #  | title                   | rating | release_date |
|   #  | Aladdin                 | G      | 25-Nov-1992  |
|   #  | The Help                | PG-13  | 10-Aug-2011  |
|   #  | Chocolat                | PG-13  | 5-Jan-2001   |
|   #  | 2001: A Space Odyssey   | G      | 6-Apr-1968   |
|   #  | Chicken Run             | G      | 21-Jun-2000  |
|   Scenario: all ratings selected                         # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/filter_movie_list.feature:50
|     Given I check the following ratings: PG, R, G, PG-13 # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/movie_steps.rb:29
|     Then I press "ratings_submit"                        # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:52
|     Then I should see all the movies                     # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/movie_steps.rb:49
| 
| Failing Scenarios:
| cucumber submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/filter_movie_list.feature:24 # Scenario: restrict to movies with 'PG' or 'R' ratings
| 
| 2 scenarios (1 failed, 1 passed)
| 12 steps (1 failed, 1 skipped, 10 passed)
| 0m0.445s
| 
|  *** ERROR: # *** 
Test failed. (-0.075)
--------------------------------------------------------------------------------
The following required failures were not detected:
 - all ratings or checkboxes selected
with the following modifications:
 - results = []
| Disabling profiles...
| Feature: display list of movies filtered by MPAA rating
|   
|   As a concerned parent
|   So that I can quickly browse movies appropriate for my family
|   I want to see movies matching only certain MPAA ratings
| 
|   Background: movies have been added to database # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/filter_movie_list.feature:7
|     Given the following movies exist:            # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/movie_steps.rb:3
|       | title                   | rating | release_date |
|       | Aladdin                 | G      | 25-Nov-1992  |
|       | The Terminator          | R      | 26-Oct-1984  |
|       | When Harry Met Sally    | R      | 21-Jul-1989  |
|       | The Help                | PG-13  | 10-Aug-2011  |
|       | Chocolat                | PG-13  | 5-Jan-2001   |
|       | Amelie                  | R      | 25-Apr-2001  |
|       | 2001: A Space Odyssey   | G      | 6-Apr-1968   |
|       | The Incredibles         | PG     | 5-Nov-2004   |
|       | Raiders of the Lost Ark | PG     | 12-Jun-1981  |
|       | Chicken Run             | G      | 21-Jun-2000  |
|     And I am on the RottenPotatoes home page     # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:44
| 
|   Scenario: restrict to movies with 'PG' or 'R' ratings # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/filter_movie_list.feature:24
|     Given I check the following ratings: PG, R          # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/movie_steps.rb:29
|     And I uncheck the following ratings: G, PG-13       # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/movie_steps.rb:29
|     Then I press "ratings_submit"                       # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:52
|     Then I should see "The Terminator"                  # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:105
|       expected to find text "The Terminator" in "Rotten Potatoes! All Movies Include: G PG PG-13 NC-17 R Movie Title Rating Release Date More Info Add new movie" (RSpec::Expectations::ExpectationNotMetError)
|       ./submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:107:in `/^(?:|I )should see "([^"]*)"$/'
|       submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/filter_movie_list.feature:33:in `Then I should see "The Terminator"'
|     But I should not see "The Help"                     # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:124
| 
|   #  And I should see
|   #  | title                   | rating | release_date |
|   #  | The Terminator          | R      | 26-Oct-1984  |
|   #  | When Harry Met Sally    | R      | 21-Jul-1989  |
|   #  | Amelie                  | R      | 25-Apr-2001  |
|   #  | The Incredibles         | PG     | 5-Nov-2004   |
|   #  | Raiders of the Lost Ark | PG     | 12-Jun-1981  |
|   #  And I should not see
|   #  | title                   | rating | release_date |
|   #  | Aladdin                 | G      | 25-Nov-1992  |
|   #  | The Help                | PG-13  | 10-Aug-2011  |
|   #  | Chocolat                | PG-13  | 5-Jan-2001   |
|   #  | 2001: A Space Odyssey   | G      | 6-Apr-1968   |
|   #  | Chicken Run             | G      | 21-Jun-2000  |
|   Scenario: all ratings selected                         # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/filter_movie_list.feature:50
|     Given I check the following ratings: PG, R, G, PG-13 # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/movie_steps.rb:29
|     Then I press "ratings_submit"                        # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/web_steps.rb:52
|     Then I should see all the movies                     # submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/step_definitions/movie_steps.rb:49
| 
| Failing Scenarios:
| cucumber submissions/d8ca89a1d3e9682e1efc16a6334af2ba/assignment3/2017-07-10-17-07-33/features/filter_movie_list.feature:24 # Scenario: restrict to movies with 'PG' or 'R' ratings
| 
| 2 scenarios (1 failed, 1 passed)
| 12 steps (1 failed, 1 skipped, 10 passed)
| 0m0.347s
| 
|  *** ERROR: # *** 
Test failed. (-0.075)
--------------------------------------------------------------------------------
Test passed. (+0.075)
--------------------------------------------------------------------------------
Test passed. (+0.075)
--------------------------------------------------------------------------------
Test passed. (+0.25)
--------------------------------------------------------------------------------
Test passed. (+0.25)
Total score: 0.8500000000000001 / 1.0
Completed in 26.450306683 seconds.
```

**Comment by an-ju** [comment] 2017-07-10 17:27
[This](https://www.dropbox.com/s/50hloir05sjpspq/features.zip?dl=0) is a working version that I changed from previous one. I changed line 35 and 39 in _/features/step_definitions/movie_step.rb_.

**Comment by tansaku** [comment] 2017-07-11 10:39
@an-ju notice the text in the output:

```
The following required failures were not detected:
 - all ratings or checkboxes selected
with the following modifications:
 - results = [G, PG-13] movies
```

```
The following required failures were not detected:
 - all ratings or checkboxes selected
with the following modifications:
 - results = []
```

We would expect all this code to pass locally.  It's failing in the autograder because the tests are not checking what they should be.  That's the point of the mutation grader; to highlight that the students have not written their tests correctly, i.e. they have vacuous tests that are passing, but don't fail when the functionality is removed ...

**Comment by an-ju** [comment] 2017-07-11 16:37
Yeah, I understand the idea of this test. But I don't think this is the cause.

In the example I gave you, by changing
`step "I uncheck \"" + "ratings_" + rating.strip + "\""`
and
`step "I check \"" + "ratings_" + rating.strip + "\""`
to
`step {I uncheck "ratings_#{rating.strip}"}`
and
`step {I check "ratings_#{rating.strip}"}`
I can get this submission to pass the auto-grader. I don't think this changes anything in essence (actually, the changed version shouldn't work because it's not syntactically valid).

Besides, another example would be changing
`check("ratings[PG]")`
to
`check('ratings_PG')`
will make a failed submission pass the auto-grader. The difference between these two submissions are only how the checkbox is located. And it seems that auto-grader doesn't support locating by value, which should be supported by the latest version of Cucumber.

**Comment by tansaku** [comment] 2017-08-22 02:06
@an-ju I'm just trying to download the files for this - but the dropbox link seems dead - can you post again or send me the relevant files on slack?

**Comment by tansaku** [comment] 2017-08-22 06:05
@an-ju I'm digging into this and both `check("ratings[PG]")` and `check('ratings_PG')` work fine for me both locally and on the grader ...

**Comment by an-ju** [comment] 2017-08-22 17:04
@tansaku I think [this](https://www.dropbox.com/s/a1aqpi6xdm3jgwd/features_failed.zip?dl=0) is the failed version, and [this](https://www.dropbox.com/s/ao37pyhoj4e8p55/features.zip?dl=0) is the working version.

**Comment by tansaku** [comment] 2017-08-25 10:44
thanks @an-ju - I can confirm the issue on the EC2 grader, although I note that locally and on the new Azure grader we don't encounter the issue, so I guess that's due to cucumber upgrade perhaps?

My diff of the two is precisely this:

```
 diff -r features_anju features_anju_failed/
Only in features_anju: .DS_Store
diff -r features_anju/step_definitions/movie_steps.rb features_anju_failed/step_definitions/movie_steps.rb
35c35
<       step {I uncheck "ratings_#{rating.strip}"}
---
>       step "I uncheck \"" + "ratings_" + rating.strip + "\""
39c39
<       step {I check "ratings_#{rating.strip}"}
---
>       step "I check \"" + "ratings_" + rating.strip + "\""
```

and it seems like this should be the same, although I note that usually I would see the cucumber `step` method used like so:

```
 step = %Q{I check "ratings_#{rating.strip}"}
```

I'm not sure how the curly braces is being interpreted by the step method - note that usually that way of specifying a string would involve a %Q or %q:

```
2.3.1 :005 > %Q{I check "ratings_#{rating.strip}"}
 => "I check \"ratings_PG\"" 
2.3.1 :006 > %q{I check "ratings_#{rating.strip}"}
 => "I check \"ratings_\#{rating.strip}\"" 
```

so I wonder if it's being interpreted as %q, but then it's not clear why both zip files work fine for me locally and on the Azure grader, unless that's a change in the ruby version of some other library ...

Anyway, perhaps this will be resolved by the move to the Azure grader ...

**Closed** 2017-11-20 15:57 UTC
